<?php

/**
 * @file
 * Contains apf_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the apf_custom module.
    case 'help.page.apf_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Views Arguments based on session, cookie or token.') . '</p>';
      return $output;

    default:
  }
}
